### ISSUE TITLE
Cannot download language pack IT

### ISSUE THREAD

**Issue by davidegurgone** [PrestaShop/docker#222] opened 2020-05-14 10:42 UTC
Hi,
i am trying to install prestashop using docker container, by running the instructions here:
https://hub.docker.com/r/prestashop/prestashop/

```bash
# create a network for containers to communicate
$ docker network create prestashop-net
# launch mysql 5.7 container
$ docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
# launch prestashop container
$ docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop
```

After creating the mysql database, I correctly started the installation steps, but it fails when try to download language pack.

To fix it I tried to automate the process by setting lang in the docker command line arg and forcing the installation, using this script:

```bash
Create Prestashop Container on port 8080
docker run -ti --name myprestashop \
	--network prestashop-net \
	-e PS_DEV_MODE=1 \
	-e DB_SERVER=prestashop-db \
	-e DB_USER=root \
	-e DB_PASSWD=xxxxxx \
	-e DB_PREFIX=ps_ \
	-e PS_DOMAIN=xxx.com \
	-e PS_LANGUAGE=it \
	-e PS_COUNTRY=IT \
	-e PS_INSTALL_AUTO=1 \
	-p 8080:80 -d prestashop/prestashop
```

Also in this way I have the same issue in commandline:
```bash
docker logs -f myprestashop         

* Checking if ista-db is available...

* DB server ista-db is available, let's continue !

* Setting up install lock file...

* Reapplying PrestaShop files for enabled volumes ...

* No pre-install script found, let's continue...

* Installing PrestaShop, this may take a while ...

* Launching the installer script...
Errors :
Cannot download language pack "it"

* No post-install script found, let's continue...

* Setup completed, removing lock file...

* Almost ! Starting web server now
```

Is there any way to fix it?
I checked around in the web but without solutions.

Thanks, Davide.

**Comment by PierreRambaud** [comment] 2021-04-01 14:44
Hi and thank for your report.
Is the problem still happen? i think it's a random error caused by the prestashop API :disappointed:

**Comment by matks** [comment] 2021-10-08 08:18
Closing as we have no answer from author.

**Closed by matks** 2021-10-08 08:18 UTC
