### ISSUE TITLE
Empty ps_employee after auto_install

### ISSUE THREAD

**Issue by SergioRius** [PrestaShop/docker#110] opened 2018-02-01 10:52 UTC
I'm trying to create a PS container in a local server, but after the installation I can't log in. Directly querying the DB (in a separate container) shows the employee table empty. This happens whenever I inform ADMIN_MAIL/_PASSWRD or not. Although some tables have contents like language, almost all the DB is empty.

My docker command is:
`
docker run --name test-prestashop 
 --link mysql 
 -e DB_SERVER=mysql 
 -e DB_USER=root 
 -e DB_PASSWD=admin 
 -e DB_NAME=test-prestashop 
 -e PS_INSTALL_AUTO=1 
 -e PS_ERASE_DB=1 
 -e PS_FOLDER_ADMIN=admin_test 
 -e PS_FOLDER_INSTALL=install_test 
 -p 8881:80 
 -e PS_DOMAIN=192.168.1.1:8881 
 -d prestashop/prestashop
`

192.168.1.1 is a docker server in my local network, and I'm browsing it from 192.168.1.1. I had to put that PS_DOMAIN so I could access it in my private network. If there's something better for it, please tell me.

**Comment by Quetzacoalt91** [comment] 2018-09-12 15:05
That issue was caused by a default but incorrect country code.

As it was fixed by https://github.com/PrestaShop/docker/pull/117, I'm closing this issue.
Regards

**Closed by Quetzacoalt91** 2018-09-12 15:05 UTC
