### ISSUE TITLE
CLI installer not respecting arguments given

### ISSUE THREAD

**Issue by bermudi** [PrestaShop/docker#81] opened 2017-06-28 05:00 UTC
`root@0088c07878be:/var/www/html/install# php index_cli.php --db_server=mysql-server --db_user=1 --db_password=something`

>`Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user 'prestashop'@'172.18.0.3' (using password: YES)`

`root@0088c07878be:/var/www/html/install# php index_cli.php --db_server=mysql-server --db_user=2 --db_password=something
`
>`Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user '1'@'172.18.0.3' (using password: YES)`

`root@0088c07878be:/var/www/html/install# php index_cli.php --db_server=mysql-server --db_user=3 --db_password=something
`
>`Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user '2'@'172.18.0.3' (using password: YES)`

Notice how the use lags one output. Also 172.18.0.3 is localhost and not mysql-server:

    root@0088c07878be:/var/www/html/install# ping mysql-server
    PING mysql-server (172.18.0.2): 56 data bytes
    64 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=0.292 ms

**Comment by khena** [comment] 2017-06-29 12:29
I think it's not a pretashop issue but a docker network or a db issue issue on your system. Do you use docker-compose ?

**Comment by bermudi** [comment] 2017-06-30 06:56
I don't think it is a network issue since I proved mysql-server does resolve without problems. The script always attempts to connect to the localhost ip no matter what parameters are passed to the script.

I used docker run [options] prestashop/prestashop to try it.

**Comment by khena** [comment] 2017-06-30 11:01
The "access denied" error for user '2' or '3' come from your mysql configuration. Can you run the
`select * from mysql.user;` to see if the user is in your database with the correct rights ? Check the Host data and re-check your password :)

Can you access to the database from outside with the same login / password ?

**Comment by Quetzacoalt91** [comment] 2017-08-10 16:28
Hello,

When you get an error like ```Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user 'prestashop'@'172.18.0.3' (using password: YES)```

The ip address is the client which tries to connect to the SQL server. Seeing `172.18.0.3` is totally expected.

On my side I'm always running the PrestaShop installation with `--db_server=mysql`, which works. By tge way, the connection can be done between your containers, because you get an authentication error, not a `server unreachable` error.

Finally, the wrong db authentication details we see in your logs seems to be caused by the current parameters file. If you delete it, or run the installation 2 times with the same parameters, you should get the proper value (although this confirm we have a bug here).

**Comment by matks** [comment] 2020-11-21 22:20
Closing as issue seems old and latest answer seems to provide accurate informations 👍

**Closed by matks** 2020-11-21 22:20 UTC
